server:
  port: ${PORT:8080}

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:postgresql:///order_db?cloudSqlInstance=global-baton-502904-d7:asia-south1:order-db-instance&amp;socketFactory=com.google.cloud.sql.postgres.SocketFactory

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false