server:
  port: ${PORT:8080}

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:postgresql://8.231.107.120:5432/order_db
    username: postgres
    password: YOUR_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    enabled: false