#server:
#  port: 8080
#
#spring:
#  application:
#    name: ORDER-SERVICE
#
#  datasource:
#    url: jdbc:postgresql://localhost:3030/order-db-application
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  kafka:
#    bootstrap-servers: localhost:9092
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#      properties:
#        spring.json.add.type.headers: false
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#  instance:
#    hostname: localhost
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      paymentService:
#        slidingWindowSize: 5
#        minimumNumberOfCalls: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        permittedNumberOfCallsInHalfOpenState: 2
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,circuitbreakers,circuitbreakerevents



    server:
      port: ${PORT:8080}

    spring:
      application:
        name: ORDER-SERVICE

      datasource:
        url: jdbc:postgresql://8.231.107.120:5432/order_db
        username: postgres
        password: 4UxS_tl$\cx~s;/5
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

      kafka:
        bootstrap-servers: localhost:9092

    eureka:
      client:
        enabled: false















